repos:
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
      args: [-w, "--ignore-words=codespell-ignore-list"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
        types_or: [c, c++]
    -   id: end-of-file-fixer
        types_or: [c, c++]
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        types_or: [c, c++]
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character
