name: Bug report
description: Report build and runtime bugs
labels: ["Type: Bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Answers checklist.
      description: Before submitting a new issue, please follow the checklist and try to find the answer.
      options:
        - label: I have read the [README](https://github.com/roma-jam/git_practice/blob/master/README.md) and the issue is not addressed there.
          required: true
        - label: I am using the target that is supported
          required: true
        - label: I have searched the [issue tracker](https://github.com/roma-jam/git_practice/issues=is%3Aissue) for a similar issue and not found any related issue.
          required: true
  - type: input
    id: devkit
    attributes:
      label: Board or Development Kit.
      description: On which Board or Development Kit does this issue occur on?
      placeholder: ex. ESP32-Wrover-Kit v2 | Custom Board
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: More Information.
      description: Do you have any other information from investigating this?
      placeholder: ex. Reproducing ratio, Nature, Dependencies etc.
    validations:
      required: false
