name: Generate Index and Deploy Pages

on:
    push:
        branches:
            - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find HTML files and generate index.html
        run: |
          mkdir -p docs
          echo "<!DOCTYPE html>" > docs/index.html
          echo "<html><head><meta charset='utf-8'><title>USBCV Reports</title></head><body>" >> docs/index.html
          echo "<h1>Available reports</h1><ul>" >> docs/index.html

          find docs -type f -name '*.html' ! -name 'index.html' | sort | while read filepath; do
            filename=$(basename "$filepath")
            echo "<li><a href=\"$filename\">$filename</a></li>" >> docs/index.html
          done

          echo "</ul></body></html>" >> docs/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
